### PR TITLE
Remove `createGraph` API

### PR DESCRIPTION
**Pull request by mikedld**
Replace it with `createTree` API for stages view; this leads to parallel stages being properly collapsed as a side-effect.

This is a take 2 on #74 which was removing the API without a proper replacement.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timbrown5** [comment]
Ah, I didn't realise the graph now uses the tree representation 🤔
If this is a departure from BlueOcean, it's worth documenting in the resdme - there seem to be a number of bugs comparing BlueOcean as the correct representation.
That said, I'm suspicious of the GraphNodeVisitor - it seems like adding the bulk of the logic to handleChunkDone could be making it more complex than it needs to be - if we assign nodes to parallel branches in parallelBranchStart then we don't need logic to check if the chunk start node is a parallel branch start.

**Comment by mikedld** [comment]
TBH I'm struggling to add support for nested parallels to current `PipelineNodeGraphVisitor` implementation and contemplating a complete rewrite exactly because the logic there seems too convoluted.

The graph is using tree representation for quite some time now (with no complaints?), and the stages view (affected by this PR) is not a feature of BlueOcea (that I know of) n so I don't think we need to care about compatibility there. Still, I'm open to suggestions on how exactly to document this.

**Comment by timbrown5** [comment]
> Still, I'm open to suggestions on how exactly to document this.

That's a good point. I was thinking of a screenshot comparison. I also realised that just because the data is structured differently it doesn't mean the front end is displaying it differently.

> I'm struggling to add support for nested parallels to current PipelineNodeGraphVisitor implementation and contemplating a complete rewrite exactly because the logic there seems too convoluted.

I had a look to see why the pipeline is not displayed correctly and struggled. There seems to be a lot of stacks that get cleared at arbitrary times.

**Comment by timja** [comment]
Tested locally looks good to me, thanks for re-doing the cleanup

**Pull request merged**
