### PR TITLE
Use tree representation for graph layout

### PR DESCRIPTION
**Pull request by mikedld**
Graph representation doesn't look correct in some cases, so use tree representation instead which appears to be proper. I didn't remove graph API endpoint in this PR as I wasn't sure if there're any plans for it, but it's unused now.

I added some tests in the frontend after the refactoring and not before just to avoid extra work of adjusting the [invalid when using graph endpoint] input test data, so basically rewriting tests that weren't there to begin with. Hopefully that's okay.

Fixes: #63

### CODE REVIEW

**Comment by DuMaM** [comment]
Could you include any screen shot, how does it look after change?

**Comment by mikedld** [comment]
@DuMaM, exactly the same as pictured in the linked issue and in the README, I'm not sure if new screenshots would make sense.

**Review by timja — APPROVED** [review]
Thanks, I think we can get rid of the graph endpoint if we aren't using it. I've tested the pipeline in the main comment and the other one further down and it fixes the issue

let's ship this

**Comment by timja** [comment]
follow up https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/74

**Comment by timja** [comment]
Seems to have made some cases worse, (related to parallel) e.g. see https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/18

(wasn't correct before either though)

**Comment by timja** [comment]
Similar issue that's now worse: https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/50

again parallel

**Pull request merged**
