### PR TITLE
Branch label positioning no longer truncated

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/31

Looking for input on this, I've came up with a couple of options,

1. Moving below and word wrapping

image

2. Moving below and having it overflow:
image

Example of non matrix build that uses a branch label:
image

Another option is to try remove swapping and extend the connections out further, I tried adjusting the width but it ended up moving the stages further to the right, which worked but looked a bit funny.

I also tried moving it to the top but that got in the way of the BuildAndTest stage name

Any thoughts ux-sig: @dduportal @MarkEWaite @fqueiruga @uhafner 

The matrix pipeline is the one from https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/

You can see one live on ci.jenkins.io at:
https://ci.jenkins.io/job/Infra/job/packer-images/job/main/lastSuccessfulBuild/pipeline-graph/

### CODE REVIEW

**Comment by timbrown5** [comment]
What happens when there are more axes in option 1 - does it infringe on the nodes of the axis below it?

**Comment by MarkEWaite** [comment]
I prefer the moving below and word wrapping (first image) over moving below and having it overflow.

**Comment by timja** [comment]
> What happens when there are more axes in option 1 - does it infringe on the nodes of the axis below it?

I made the font smaller and some other minor tweaks, here's some screenshots with differing numbers of axes

image

image


image

**Comment by zbynek** [comment]
would it make sense to provide some short name of the stage? Maybe just `matrix (linux, chrome)` without the variable names, with more information available on click.

**Comment by timja** [comment]
> would it make sense to provide some short name of the stage? Maybe just `matrix (linux, chrome)` without the variable names, with more information available on click.

good idea, any thoughts @bitwiseman ?

**Comment by timja** [comment]
To add another parameter 
https://github.com/jenkinsci/workflow-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/actions/LabelAction.java would need to be updated.

Alternatively it could be updated in https://github.com/jenkinsci/pipeline-model-definition-plugin (somewhere) to have a shorter name.

Any thoughts?

**Comment by lhupfeldt** [comment]
At some point you would probably like to truncate very long stage names. I think truncating (at approximately the current lengt) is fine if the mouse-over would display the full stage name instead of the truncated name. What is the point  in a mouse-over displaying the same text which is already on screen?
Granting the user some control over truncation (default length and maybe per stage as well) and having explicit mouse-over text would be nice, but I think simply fixing the mouse-over would satisfy a lot of people.

**Comment by timja** [comment]
Worked around with tooltip for now

**Pull request closed without merging**
