### PR TITLE
fix(overview): don't restrict width and height

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR removes width and height restriction on the Pipeline Overview page.

From https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/135#issuecomment-1439166780, https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/135#issuecomment-1439704382 & https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/197#issuecomment-1320228179

> it's planned to add more cards there

> > Extensible cards by any chance?
>
> By plugins, yes that's the plan, they aren't currently.

> [...] possibly other buttons in future, see https://jenkins-redesign.vercel.app/project/build/375

As there isn't any additional cards yet, I've removed the last reserved grid column to regain some width, can be revised when/if the situation evolves.

<details><summary>Before:</summary>

image

</details>

<details><summary>After:</summary>

image

</details>

<details><summary>Screen width < 1700px:</summary>

image

</details>

Related: #135, #277

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by lemeurherve** [comment]
I've noticed that by removing the `app-page-body--one-column` CSS class from the `page-body` div we can gain some more width, but didn't find how to do it in this plugin (yet).

<details><summary>With "app-page-body--one-column" CSS class (this PR, for ref):</summary>

image

</details>

<details><summary>Without "app-page-body--one-column" CSS class</summary>

image

</details>

**Review by timja — APPROVED** [review]
thanks I think ok, let's see how it goes. 

I've adjusted the margins as you mentioned in https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/299#issuecomment-1751403150

Pipeline console for some reason is a bit further to the left not sure why but it seems ok

**Comment by lemeurherve** [comment]
Oh I didn't realize this width came from the CSS of this plugin, thanks for the additional commits @timja!

**Comment by timja** [comment]
> Oh I didn't realize this width came from the CSS of this plugin, thanks for the additional commits @timja!

it didn't, it's a core style but these pages are isolated so they can override it

**Pull request merged**
